# Generated by Django 4.0.3 on 2022-03-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book',
        ),
    ]
