# Generated by Django 4.0.2 on 2022-02-26 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLU', 'Blue'), ('YEL', 'Yellow'), ('BLA', 'Black'), ('WHI', 'White')], max_length=3)),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('fuel', models.CharField(choices=[('DIE', 'Diesel'), ('PET', 'Petrol'), ('HYB', 'Hybrid'), ('LPG', 'LPG'), ('ELE', 'Electric')], max_length=3)),
                ('power', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='CarMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cardetail')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmain')),
            ],
        ),
    ]
