# Generated by Django 4.0.2 on 2022-03-09 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_post_comment_car_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 22, 4, 59, 135097, tzinfo=utc)),
        ),
    ]
