# Generated by Django 4.0.3 on 2022-03-11 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_comment_approved_comment_alter_comment_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 20, 36, 52, 61300, tzinfo=utc)),
        ),
    ]
