# Generated by Django 4.0.3 on 2022-03-12 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_comment_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 16, 12, 55, 969004, tzinfo=utc)),
        ),
    ]
