# Generated by Django 4.0.3 on 2022-03-12 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_cardetail_image_car_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 19, 36, 58, 744965, tzinfo=utc)),
        ),
    ]
