# Generated by Django 4.0.3 on 2022-03-14 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_comment_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmain',
            old_name='marka',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 18, 54, 11, 507922, tzinfo=utc)),
        ),
    ]
